### ISSUE TITLE
Unexpected End of JSON input

### ISSUE THREAD

**Issue by ghost** [imzoloft/soundcheck#1]
Whenever I run it instead of checking the emails I get a Unexpected End of JSON input

[image](https://github.com/imzoloft/soundcheck/assets/90668727/907cac20-f8b5-4017-ba58-d89b45f8613f)

**Comment by notlplavoie** [comment]
Hello,

Thank you for addressing the issue. It's great to hear that you've hardcoded the client_id and that it's working on your end now. However, regarding the expiration of the client_id, it's essential to confirm whether it remains valid indefinitely or if it expires after a certain period.

If the client_id does expire, you may indeed need to implement a mechanism to scrape it dynamically or find another solution to ensure the continued functionality of your application.

In any case, I appreciate your prompt attention to the matter, and I'll close this issue for now. Please feel free to open a new one or reach out to me via Discord if any further problems arise.

Best regards.
